# Generated by Django 2.2.6 on 2020-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_filljointable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='five_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='four_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='one_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='three_star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='two_star',
            field=models.IntegerField(null=True),
        ),
    ]
