# Generated by Django 2.2.6 on 2020-04-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200328_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='five_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='four_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='one_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='three_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='two_star',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Large', 'XXL'), ('Triple Large', 'XXXL')], max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete='on_delete', to='shop.Product')),
            ],
        ),
    ]
